import { StoreProjectV2Schema } from "./index";

const now = "2026-07-29T12:00:00.000Z";

export const referenceStore = StoreProjectV2Schema.parse({
  schemaVersion: 2,
  id: "store-casa-luma",
  name: "Tienda Referencia",
  slug: "tienda-referencia",
  status: "active",
  locale: "es-AR",
  currency: "ARS",
  priceFractionDisplay: "always",
  baseUrl: "https://tienda-referencia.example",
  createdAt: now,
  updatedAt: now,
  identity: {
    legalName: "Tienda Referencia Objetos SRL",
    brandName: "Tienda Referencia",
    description: "Objetos cotidianos elegidos por su materia, uso y permanencia.",
    email: "hola@tienda-referencia.example",
    phone: "5491123456789",
    address: "Buenos Aires, Argentina",
  },
  whatsapp: {
    phone: "5491123456789",
    greeting: "Hola Tienda Referencia, quiero hacer este pedido:",
    includeSku: true,
  },
  seo: {
    title: "Tienda Referencia | Objetos para todos los días",
    description: "Objetos de mesa, textiles y piezas de autor seleccionadas en Buenos Aires.",
    searchConsoleVerification: "",
    merchantVerification: "",
  },
  theme: {
    colorMode: "auto",
    colors: {
      background: "#f5f0e6",
      surface: "#e9e1d3",
      text: "#25271f",
      muted: "#6e6b5f",
      accent: "#4b6246",
      accentText: "#fbf7ee",
      border: "#cec5b5",
    },
    typography: {
      display: "Palatino, 'Palatino Linotype', Georgia, serif",
      body: "'Segoe UI', Aptos, Arial, sans-serif",
      scale: 1,
    },
    spacingScale: 1,
    radius: 4,
    container: 1360,
  },
  navigation: {
    catalogLabel: "Colecciones",
    showHome: true,
    showContact: true,
    showAbout: true,
    showSearch: true,
    showCart: true,
    items: [
      {
        id: "nav-casa",
        label: "Casa",
        href: "/categorias/mesa/",
        children: [
          { id: "nav-textiles", label: "Textiles", href: "/categorias/textiles/" },
          { id: "nav-mesa", label: "Mesa", href: "/categorias/mesa/" },
        ],
      },
    ],
  },
  siteShell: { announcement: true, header: true, footer: true, cart: true },
  commerceTemplates: {
    category: { productsPerPage: 24 },
    search: { enabled: true },
    product: { showRelated: true },
    cart: { enabled: true },
    checkout: { enabled: true },
  },
  pages: [
    {
      id: "page-home",
      kind: "home",
      slug: "inicio",
      title: "Una casa con materia y calma.",
      seoTitle: "Tienda Referencia | Objetos para todos los días",
      seoDescription: "Objetos de mesa, textiles y piezas de autor seleccionadas en Buenos Aires.",
      sections: [],
    },
    {
      id: "page-about",
      kind: "about",
      slug: "nosotros",
      title: "Elegimos objetos para vivirlos.",
      seoTitle: "Nosotros | Tienda Referencia",
      seoDescription:
        "Conocé la mirada detrás de la tienda de referencia y las piezas que elegimos.",
      sections: [],
    },
    {
      id: "page-contact",
      kind: "contact",
      slug: "contacto",
      title: "Estamos para ayudarte.",
      seoTitle: "Contacto | Tienda Referencia",
      seoDescription: "Escribinos por WhatsApp, email o teléfono para coordinar tu pedido.",
      sections: [],
    },
  ],
  policies: {
    shipping: {
      summary: "Envíos a todo el país.",
      details: "Coordinamos el envío y su costo antes de confirmar el pedido.",
      countries: ["AR"],
      handlingDaysMin: 1,
      handlingDaysMax: 3,
      transitDaysMin: 2,
      transitDaysMax: 7,
      returnDays: 10,
    },
    returns: {
      summary: "Cambios dentro de los 10 días.",
      details: "La pieza debe conservar su embalaje y no presentar señales de uso.",
      countries: ["AR"],
      handlingDaysMin: 0,
      handlingDaysMax: 1,
      transitDaysMin: 0,
      transitDaysMax: 0,
      returnDays: 10,
    },
    privacy: "Usamos tus datos únicamente para responder y coordinar el pedido.",
    terms: "Los precios y la disponibilidad se confirman antes del pago.",
  },
  assets: [
    {
      kind: "image",
      id: "asset-manta",
      name: "Manta Bruma",
      alt: "Manta de algodón verde sobre un sillón claro",
      mimeType: "image/jpeg",
      source: "/fixtures/manta-bruma.png",
      width: 1152,
      height: 1536,
      hash: "fixture-manta",
    },
    {
      kind: "image",
      id: "asset-jarra",
      name: "Jarra Delta",
      alt: "Jarra de cerámica sobre una mesa de madera",
      mimeType: "image/jpeg",
      source: "/fixtures/jarra-delta.png",
      width: 1152,
      height: 1536,
      hash: "fixture-jarra",
    },
    {
      kind: "image",
      id: "asset-hero",
      name: "Mesa de referencia",
      alt: "Mesa servida con objetos de referencia",
      mimeType: "image/jpeg",
      source: "/fixtures/casa-luma-hero.png",
      width: 1536,
      height: 1024,
      hash: "fixture-hero",
    },
  ],
  videos: [],
  products: [
    {
      id: "product-manta-bruma",
      slug: "manta-bruma",
      title: "Manta Bruma",
      description: "Algodón peinado, trama liviana y terminación artesanal.",
      status: "active",
      brand: "Tienda Referencia",
      categoryIds: ["category-textiles"],
      collectionIds: ["collection-casa-serena"],
      tags: ["algodón", "textil"],
      imageIds: ["asset-manta"],
      variants: [
        {
          id: "variant-manta-musgo",
          sku: "ML-BRU-MUS",
          title: "Musgo",
          optionValues: { Color: "Musgo" },
          price: 7850000,
          compareAtPrice: 8490000,
          available: true,
          stockStatus: "in_stock",
          gtin: "7791234567012",
          imageId: "asset-manta",
        },
        {
          id: "variant-manta-piedra",
          sku: "ML-BRU-PIE",
          title: "Piedra",
          optionValues: { Color: "Piedra" },
          price: 7850000,
          available: true,
          stockStatus: "in_stock",
          gtin: "7791234567029",
          imageId: "asset-manta",
        },
      ],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "product-jarra-delta",
      slug: "jarra-delta",
      title: "Jarra Delta",
      description: "Cerámica esmaltada en pequeños lotes. Capacidad de 1,2 litros.",
      status: "active",
      brand: "Taller Nadir",
      categoryIds: ["category-mesa"],
      collectionIds: ["collection-casa-serena"],
      tags: ["cerámica", "mesa"],
      imageIds: ["asset-jarra"],
      variants: [
        {
          id: "variant-jarra-unica",
          sku: "JD-12-CRU",
          title: "Crudo",
          optionValues: { Color: "Crudo" },
          price: 4620000,
          available: true,
          stockStatus: "in_stock",
          mpn: "JD-12-CRU",
          imageId: "asset-jarra",
        },
      ],
      createdAt: now,
      updatedAt: now,
    },
  ],
  categories: [
    {
      id: "category-textiles",
      slug: "textiles",
      title: "Textiles",
      description: "Capas suaves para el uso diario.",
      imageId: "asset-manta",
      productIds: ["product-manta-bruma"],
    },
    {
      id: "category-mesa",
      slug: "mesa",
      title: "Mesa",
      description: "Piezas útiles que ganan carácter con el tiempo.",
      imageId: "asset-jarra",
      productIds: ["product-jarra-delta"],
    },
  ],
  collections: [
    {
      id: "collection-casa-serena",
      slug: "casa-serena",
      title: "Casa serena",
      description: "Una selección para bajar el ritmo sin perder utilidad.",
      imageId: "asset-hero",
      productIds: ["product-manta-bruma", "product-jarra-delta"],
    },
  ],
  sections: [
    {
      id: "section-announcement",
      slot: "announcement",
      moduleId: "announcement-bar",
      enabled: true,
      settings: { text: "Envíos a todo el país" },
      motion: {
        preset: "none",
        intensity: 0,
        direction: "up",
        distance: 0,
        duration: 0,
        delay: 0,
        stagger: 0,
        easing: "linear",
        entryPoint: 0.3,
        once: true,
      },
    },
    {
      id: "section-header",
      slot: "header",
      moduleId: "editorial-header",
      enabled: true,
      settings: {},
      motion: {
        preset: "none",
        intensity: 0,
        direction: "up",
        distance: 0,
        duration: 0,
        delay: 0,
        stagger: 0,
        easing: "linear",
        entryPoint: 0.3,
        once: true,
      },
    },
    {
      id: "section-hero",
      slot: "hero",
      moduleId: "hero-media",
      enabled: true,
      settings: {
        eyebrow: "Objetos elegidos con tiempo",
        title: "Una casa con materia y calma.",
        body: "Piezas honestas para usar todos los días.",
        actionLabel: "Ver colección",
        actionHref: "/categorias/textiles/",
        mode: "image",
        posterAssetId: "asset-hero",
        overlay: "dark",
        alignment: "left",
        autoplay: false,
        intervalMs: 6000,
        slides: [],
      },
      motion: {
        preset: "fade-up",
        intensity: 5,
        direction: "up",
        distance: 28,
        duration: 0.7,
        delay: 0,
        stagger: 0.08,
        easing: "cubic-bezier(.16,1,.3,1)",
        entryPoint: 0.25,
        once: true,
      },
    },
    {
      id: "section-products",
      slot: "catalog",
      moduleId: "compact-product-grid",
      enabled: true,
      settings: { title: "Productos destacados", limit: 12 },
      motion: {
        preset: "stagger",
        intensity: 5,
        direction: "up",
        distance: 20,
        duration: 0.55,
        delay: 0,
        stagger: 0.07,
        easing: "cubic-bezier(.16,1,.3,1)",
        entryPoint: 0.2,
        once: true,
      },
    },
    {
      id: "section-collections",
      slot: "catalog",
      moduleId: "collection-grid",
      enabled: true,
      settings: { title: "Comprar por ambiente" },
      motion: {
        preset: "stagger",
        intensity: 5,
        direction: "up",
        distance: 20,
        duration: 0.55,
        delay: 0,
        stagger: 0.08,
        easing: "cubic-bezier(.16,1,.3,1)",
        entryPoint: 0.2,
        once: true,
      },
    },
    {
      id: "section-story",
      slot: "content",
      moduleId: "image-text-content",
      enabled: true,
      settings: {
        title: "La materia también cuenta una historia.",
        body: "<p>Una selección precisa para usar, regalar y volver a elegir.</p>",
        imageId: "asset-jarra",
        imageSide: "right",
        actionLabel: "Conocé nuestra mirada",
        actionHref: "/nosotros/",
      },
      motion: {
        preset: "fade-up",
        intensity: 4,
        direction: "up",
        distance: 24,
        duration: 0.6,
        delay: 0,
        stagger: 0,
        easing: "cubic-bezier(.16,1,.3,1)",
        entryPoint: 0.2,
        once: true,
      },
    },
    {
      id: "section-trust",
      slot: "trust",
      moduleId: "trust-strip",
      enabled: true,
      settings: {},
      motion: {
        preset: "fade",
        intensity: 4,
        direction: "up",
        distance: 0,
        duration: 0.5,
        delay: 0,
        stagger: 0,
        easing: "ease-out",
        entryPoint: 0.3,
        once: true,
      },
    },
    {
      id: "section-cart",
      slot: "cart",
      moduleId: "cart-drawer",
      enabled: true,
      settings: {},
      motion: {
        preset: "none",
        intensity: 0,
        direction: "up",
        distance: 0,
        duration: 0,
        delay: 0,
        stagger: 0,
        easing: "linear",
        entryPoint: 0.3,
        once: true,
      },
    },
    {
      id: "section-footer",
      slot: "footer",
      moduleId: "editorial-footer",
      enabled: true,
      settings: {},
      motion: {
        preset: "none",
        intensity: 0,
        direction: "up",
        distance: 0,
        duration: 0,
        delay: 0,
        stagger: 0,
        easing: "linear",
        entryPoint: 0.3,
        once: true,
      },
    },
  ],
});
