import { StoreProjectV1Schema } from "./index";

const now = "2026-07-29T12:00:00.000Z";

export const referenceStore = StoreProjectV1Schema.parse({
  schemaVersion: 1,
  id: "store-casa-luma",
  name: "Casa Luma",
  slug: "casa-luma",
  status: "active",
  locale: "es-AR",
  currency: "ARS",
  baseUrl: "https://casa-luma.example",
  createdAt: now,
  updatedAt: now,
  identity: {
    legalName: "Casa Luma Objetos SRL",
    brandName: "Casa Luma",
    description: "Objetos cotidianos elegidos por su materia, uso y permanencia.",
    email: "hola@casa-luma.example",
    phone: "5491123456789",
    address: "Buenos Aires, Argentina",
  },
  whatsapp: {
    phone: "5491123456789",
    greeting: "Hola Casa Luma, quiero hacer este pedido:",
    includeSku: true,
  },
  seo: {
    title: "Casa Luma | Objetos para todos los días",
    description: "Objetos de mesa, textiles y piezas de autor seleccionadas en Buenos Aires.",
    searchConsoleVerification: "",
    merchantVerification: "",
  },
  theme: {
    colorMode: "auto",
    colors: {
      background: "#f4f3ee",
      surface: "#e9e7df",
      text: "#17211c",
      muted: "#667069",
      accent: "#2e6b4f",
      accentText: "#f7f5ef",
      border: "#c9cec8",
    },
    typography: {
      display: "Georgia, 'Times New Roman', serif",
      body: "'Segoe UI', Arial, sans-serif",
      scale: 1,
    },
    spacingScale: 1,
    radius: 6,
    container: 1320,
  },
  policies: {
    shipping: {
      summary: "Envíos a todo el país.",
      details: "Coordinamos el envío y su costo antes de confirmar el pedido.",
      countries: ["AR"],
      handlingDaysMin: 1,
      handlingDaysMax: 3,
      transitDaysMin: 2,
      transitDaysMax: 7,
      returnDays: 10,
    },
    returns: {
      summary: "Cambios dentro de los 10 días.",
      details: "La pieza debe conservar su embalaje y no presentar señales de uso.",
      countries: ["AR"],
      handlingDaysMin: 0,
      handlingDaysMax: 1,
      transitDaysMin: 0,
      transitDaysMax: 0,
      returnDays: 10,
    },
    privacy: "Usamos tus datos únicamente para responder y coordinar el pedido.",
    terms: "Los precios y la disponibilidad se confirman antes del pago.",
  },
  assets: [
    {
      id: "asset-manta",
      name: "Manta Bruma",
      alt: "Manta de algodón verde sobre un sillón claro",
      mimeType: "image/jpeg",
      source: "/fixtures/manta-bruma.png",
      width: 1152,
      height: 1536,
      hash: "fixture-manta",
    },
    {
      id: "asset-jarra",
      name: "Jarra Delta",
      alt: "Jarra de cerámica sobre una mesa de madera",
      mimeType: "image/jpeg",
      source: "/fixtures/jarra-delta.png",
      width: 1152,
      height: 1536,
      hash: "fixture-jarra",
    },
    {
      id: "asset-hero",
      name: "Mesa Casa Luma",
      alt: "Mesa servida con objetos de Casa Luma",
      mimeType: "image/jpeg",
      source: "/fixtures/casa-luma-hero.png",
      width: 1536,
      height: 1024,
      hash: "fixture-hero",
    },
  ],
  products: [
    {
      id: "product-manta-bruma",
      slug: "manta-bruma",
      title: "Manta Bruma",
      description: "Algodón peinado, trama liviana y terminación artesanal.",
      status: "active",
      brand: "Casa Luma",
      categoryIds: ["category-textiles"],
      collectionIds: ["collection-casa-serena"],
      tags: ["algodón", "textil"],
      imageIds: ["asset-manta"],
      variants: [
        {
          id: "variant-manta-musgo",
          sku: "ML-BRU-MUS",
          title: "Musgo",
          optionValues: { Color: "Musgo" },
          price: 7850000,
          compareAtPrice: 8490000,
          available: true,
          stockStatus: "in_stock",
          gtin: "7791234567012",
          imageId: "asset-manta",
        },
        {
          id: "variant-manta-piedra",
          sku: "ML-BRU-PIE",
          title: "Piedra",
          optionValues: { Color: "Piedra" },
          price: 7850000,
          available: true,
          stockStatus: "in_stock",
          gtin: "7791234567029",
          imageId: "asset-manta",
        },
      ],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "product-jarra-delta",
      slug: "jarra-delta",
      title: "Jarra Delta",
      description: "Cerámica esmaltada en pequeños lotes. Capacidad de 1,2 litros.",
      status: "active",
      brand: "Taller Nadir",
      categoryIds: ["category-mesa"],
      collectionIds: ["collection-casa-serena"],
      tags: ["cerámica", "mesa"],
      imageIds: ["asset-jarra"],
      variants: [
        {
          id: "variant-jarra-unica",
          sku: "JD-12-CRU",
          title: "Crudo",
          optionValues: { Color: "Crudo" },
          price: 4620000,
          available: true,
          stockStatus: "in_stock",
          mpn: "JD-12-CRU",
          imageId: "asset-jarra",
        },
      ],
      createdAt: now,
      updatedAt: now,
    },
  ],
  categories: [
    {
      id: "category-textiles",
      slug: "textiles",
      title: "Textiles",
      description: "Capas suaves para el uso diario.",
      imageId: "asset-manta",
      productIds: ["product-manta-bruma"],
    },
    {
      id: "category-mesa",
      slug: "mesa",
      title: "Mesa",
      description: "Piezas útiles que ganan carácter con el tiempo.",
      imageId: "asset-jarra",
      productIds: ["product-jarra-delta"],
    },
  ],
  collections: [
    {
      id: "collection-casa-serena",
      slug: "casa-serena",
      title: "Casa serena",
      description: "Una selección para bajar el ritmo sin perder utilidad.",
      imageId: "asset-hero",
      productIds: ["product-manta-bruma", "product-jarra-delta"],
    },
  ],
  sections: [
    {
      id: "section-announcement",
      slot: "announcement",
      moduleId: "announcement-bar",
      enabled: true,
      settings: { text: "Envíos a todo el país" },
      motion: {
        preset: "none",
        intensity: 0,
        direction: "up",
        distance: 0,
        duration: 0,
        delay: 0,
        stagger: 0,
        easing: "linear",
        entryPoint: 0.3,
        once: true,
      },
    },
    {
      id: "section-header",
      slot: "header",
      moduleId: "editorial-header",
      enabled: true,
      settings: {},
      motion: {
        preset: "none",
        intensity: 0,
        direction: "up",
        distance: 0,
        duration: 0,
        delay: 0,
        stagger: 0,
        easing: "linear",
        entryPoint: 0.3,
        once: true,
      },
    },
    {
      id: "section-hero",
      slot: "hero",
      moduleId: "split-hero",
      enabled: true,
      settings: {
        eyebrow: "Objetos elegidos con tiempo",
        title: "Una casa con materia y calma.",
        body: "Piezas honestas para usar todos los días.",
        actionLabel: "Ver colección",
        actionHref: "/categorias/textiles/",
        imageId: "asset-hero",
      },
      motion: {
        preset: "fade-up",
        intensity: 5,
        direction: "up",
        distance: 28,
        duration: 0.7,
        delay: 0,
        stagger: 0.08,
        easing: "cubic-bezier(.16,1,.3,1)",
        entryPoint: 0.25,
        once: true,
      },
    },
    {
      id: "section-collections",
      slot: "catalog",
      moduleId: "collection-grid",
      enabled: true,
      settings: { title: "Comprar por ambiente" },
      motion: {
        preset: "stagger",
        intensity: 5,
        direction: "up",
        distance: 20,
        duration: 0.55,
        delay: 0,
        stagger: 0.08,
        easing: "cubic-bezier(.16,1,.3,1)",
        entryPoint: 0.2,
        once: true,
      },
    },
    {
      id: "section-products",
      slot: "catalog",
      moduleId: "editorial-product-grid",
      enabled: true,
      settings: { title: "Selección de temporada", limit: 8 },
      motion: {
        preset: "stagger",
        intensity: 5,
        direction: "up",
        distance: 20,
        duration: 0.55,
        delay: 0,
        stagger: 0.07,
        easing: "cubic-bezier(.16,1,.3,1)",
        entryPoint: 0.2,
        once: true,
      },
    },
    {
      id: "section-trust",
      slot: "trust",
      moduleId: "trust-strip",
      enabled: true,
      settings: {},
      motion: {
        preset: "fade",
        intensity: 4,
        direction: "up",
        distance: 0,
        duration: 0.5,
        delay: 0,
        stagger: 0,
        easing: "ease-out",
        entryPoint: 0.3,
        once: true,
      },
    },
    {
      id: "section-cart",
      slot: "cart",
      moduleId: "cart-drawer",
      enabled: true,
      settings: {},
      motion: {
        preset: "none",
        intensity: 0,
        direction: "up",
        distance: 0,
        duration: 0,
        delay: 0,
        stagger: 0,
        easing: "linear",
        entryPoint: 0.3,
        once: true,
      },
    },
    {
      id: "section-footer",
      slot: "footer",
      moduleId: "editorial-footer",
      enabled: true,
      settings: {},
      motion: {
        preset: "none",
        intensity: 0,
        direction: "up",
        distance: 0,
        duration: 0,
        delay: 0,
        stagger: 0,
        easing: "linear",
        entryPoint: 0.3,
        once: true,
      },
    },
  ],
});
