/**
 * Texto global visible en el storefront. El copy específico de cada módulo
 * sigue viviendo en StoreSection.settings; este bloque cubre los controles y
 * estados compartidos que antes tenían fallbacks repartidos por los renderers.
 */
export const PUBLIC_COPY_DEFAULTS = {
  navigation: {
    home: "Inicio",
    catalog: "Categorías",
    contact: "Contacto",
    about: "Nosotros",
    search: "Buscar productos",
    cart: "Carrito",
    viewAll: "Ver todos los productos",
    openMenu: "Abrir menú",
    closeMenu: "Cerrar menú",
    close: "Cerrar",
  },
  search: {
    title: "Buscar productos",
    placeholder: "Buscar productos...",
    queryLabel: "Buscá por nombre, marca, categoría o etiqueta.",
    submit: "Buscar",
    close: "Cerrar búsqueda",
    empty: "Elegí una búsqueda",
    queryTooShort: "Escribí al menos 2 caracteres para buscar.",
    loading: "Cargando resultados…",
    noResults: "No encontramos productos para esa búsqueda.",
    suggestion: "No encontramos resultados para “{query}”. ¿Quisiste decir",
    error: "No se pudo cargar la búsqueda. Intentá nuevamente.",
  },
  filters: {
    title: "Filtros",
    availability: "Disponibilidad",
    availableOnly: "Sólo disponibles",
    tag: "Etiqueta",
    filterByTag: "Filtrar por etiqueta",
    all: "Todas",
    price: "Precio",
    minimum: "Mínimo",
    maximum: "Máximo",
    sort: "Ordenar",
    recommended: "Recomendados",
    priceAsc: "Precio menor",
    priceDesc: "Precio mayor",
    name: "Nombre",
    resultCount: "productos",
  },
  hero: {
    benefits: "Beneficios",
    activeProducts: "productos activos",
    categories: "categorías",
    whatsapp: "WhatsApp",
    contact: "Contacto",
    directOrder: "pedido directo",
    inquiries: "consultas",
    whatsappAction: "Escribir por WhatsApp",
    pauseVideo: "Pausar video",
    resumeVideo: "Reanudar video",
    slidePrev: "Slide anterior",
    slideNext: "Slide siguiente",
  },
  errors: {
    catalogLoad: "No se pudo cargar el catálogo.",
    searchIndexLoad: "No se pudo cargar el índice de búsqueda.",
  },
  product: {
    available: "Disponible",
    outOfStock: "Agotado",
    from: "Desde",
    variant: "Variante",
    quantity: "Cantidad",
    sku: "SKU",
    availability: "Disponibilidad",
    details: "Detalles",
    policies: "Envíos y cambios",
    shipping: "Envíos",
    returns: "Cambios y devoluciones",
    askWhatsApp: "Consultar por WhatsApp",
    addToCart: "Agregar al carrito",
    noStock: "Sin stock",
    related: "También puede interesarte",
    options: "Opciones del producto",
    reviews: "Reseñas",
    reviewEyebrow: "Experiencias reales",
    reviewTitle: "Lo que dicen quienes compraron",
    verifiedPurchase: "Compra verificada",
  },
  contact: {
    whatsappFallback: "Configurá un teléfono de WhatsApp para recibir consultas.",
    emailFallback: "Configurá un email para recibir consultas.",
    emailAction: "Enviar consulta por email",
    success: "Listo",
    email: "Email",
    phone: "Teléfono",
    whatsapp: "WhatsApp",
    address: "Dirección",
    whatsappAction: "Escribir por WhatsApp",
    reason: "Motivo",
    orderNumber: "Número de pedido",
    message: "Mensaje",
    emailSubject: "Consulta para {storeName}",
  },
  cart: {
    close: "Cerrar carrito",
    continueShopping: "Seguir comprando",
    subtotal: "Subtotal",
    delivery: "Entrega",
    deliveryToCoordinate: "A coordinar",
    estimatedTotal: "Total estimado",
    name: "Nombre",
    phone: "Teléfono",
    address: "Dirección o punto de entrega",
    locality: "Localidad / Provincia",
    postalCode: "Código postal",
    notes: "Notas opcionales",
    remove: "Eliminar",
    unavailable: "Ya no disponible",
    exploreCategories: "Explorar categorías",
    phoneInvalid: "Ingresá un teléfono válido",
  },
  checkout: {
    submit: "Preparar pedido",
    sendWhatsApp: "Enviar pedido en WhatsApp",
    coordinate: "Escribinos para coordinar",
    continue: "Continuar a compra",
    summary: "Resumen del pedido",
    selection: "Tu selección",
    prepare: "Prepará el pedido para revisar productos y total antes de abrir WhatsApp.",
    invalidItems: "Retirá los productos no disponibles del carrito antes de enviar el pedido.",
    emptyCart: "Tu carrito está vacío: agregá productos antes de preparar el pedido.",
    total: "Total estimado",
    delivery: "Entrega",
    disclaimer: "Entiendo que precio, disponibilidad, envío y pago se confirman por este medio.",
  },
  footer: {
    explore: "Explorar",
    help: "Ayuda",
    contact: "Contacto",
    policies: "Políticas",
    shipping: "Envíos",
    returns: "Cambios",
    privacy: "Privacidad",
    terms: "Términos",
    copyright: "Todos los derechos reservados.",
  },
  empty: {
    products: "No hay productos para mostrar.",
    collections: "Todavía no hay colecciones publicadas.",
    cart: "Tu carrito está vacío.",
    filteredProducts: "No hay productos que coincidan con estos filtros.",
  },
  pages: {
    home: "Inicio",
    catalog: "Catálogo",
    products: "Productos",
    categories: "Categorías",
    search: "Buscar",
    cart: "Carrito",
    checkout: "Compra",
    about: "Nosotros",
    contact: "Contacto",
    shipping: "Envíos",
    returns: "Cambios y devoluciones",
    privacy: "Privacidad",
    terms: "Términos",
    notFound: "Página no encontrada",
    shippingDeliveryInfo: "Información de entrega",
    shippingPreparation: "Preparación del pedido",
    shippingTransit: "Tiempo estimado de tránsito",
    policyCoverage: "Cobertura",
    returnsConditions: "Condiciones de cambio",
    returnsInformedPeriod: "Plazo informado",
    privacyDataUsage: "Uso de tus datos",
    privacyDescription: "Cómo usamos los datos compartidos al realizar un pedido.",
    termsSubtitle: "Información vigente para coordinar una compra.",
    termsDescription: "Condiciones comerciales de la tienda.",
    aboutEyebrow: "Nuestra mirada",
    aboutFallbackTitle: "Elegimos objetos para vivirlos.",
    aboutGuidanceTitle: "Lo que nos guía",
    aboutInformationTitle: "Información clara",
    aboutContactAction: "Conocé cómo contactarnos",
    aboutSelectionTitle: "Selección",
    aboutSelectionFallback: "Conocé nuestras colecciones.",
    aboutDeliveryTitle: "Entrega",
    aboutDirectTitle: "Atención directa",
    aboutDirectFallback: "Escribinos para recibir asesoramiento.",
    contactEyebrow: "Hablemos",
    contactFallbackTitle: "Estamos para ayudarte.",
    contactDescription:
      "Respondemos consultas, disponibilidad y detalles de entrega por canales directos.",
    contactPurchaseTitle: "Coordinemos tu compra",
    contactPurchaseDescription:
      "Si ya elegiste una pieza, podés escribirnos y te confirmamos disponibilidad, envío y pago.",
    notFoundEyebrow: "Página no encontrada",
    notFoundTitle: "No encontramos esa página.",
    notFoundDescription: "Podés volver al inicio o explorar nuestras colecciones.",
    returnHome: "Volver al inicio",
    viewCategories: "Ver categorías",
  },
  whatsapp: {
    ask: "Hola {storeName}, quiero hacer una consulta.",
    purchase: "Hola {storeName}, quiero coordinar una compra.",
    orderGreeting: "Hola {storeName}, quiero hacer este pedido:",
    product: "Producto",
    variant: "Variante",
    price: "Precio",
    total: "Total estimado",
    customerName: "Nombre",
    customerPhone: "Teléfono",
    delivery: "Entrega",
    notes: "Notas",
    confirmation: "Entiendo que precio, disponibilidad, envío y pago se confirman por este medio.",
  },
  export: {
    skipToContent: "Ir al contenido",
    breadcrumbs: "Migas de pan",
    pagination: "Paginación",
    previous: "Anterior",
    next: "Siguiente",
    pageOf: "Página {page} de {total}",
    categoryChildren: "Subcategorías de {category}",
    exploreCategory: "Explorar {category}",
    categoryProducts: "productos",
    viewCollection: "Ver colección",
    viewImage: "Ver imagen {index}",
    variantLinks: "Enlaces directos a variantes",
    policyDetailsTitle: "Qué necesitás saber",
    policyQuestionsTitle: "¿Tenés dudas?",
    policyQuestionsBody:
      "Escribinos antes de coordinar tu pedido y revisamos esta información con vos.",
  },
  accessibility: {
    benefits: "Beneficios",
    productInfo: "Información del producto",
    catalogSummary: "Resumen del catálogo",
    mobileNavigation: "Navegación móvil",
    mainNavigation: "Navegación principal",
    announcements: "Avisos",
    heroSlides: "Slides del hero",
    goToSlide: "Ir al slide {index}",
  },
};
